# Generated by Django 3.2.16 on 2022-11-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='host',
            name='code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
